{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "android-tv-sdk",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:environment": "production",
        "environment": "production",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-tv-sdk-0.1.1.aar",
          "url": "android-tv-sdk-0.1.1.aar",
          "size": 58722,
          "sha512": "dd743d28cd1db5b988bcce13f4f8f1771d20971429425753a630f9d9fcf4fe17131bbf87f88271f5f6e61194067a650759a4dce8ee6236e1ca57a27efa5e2561",
          "sha256": "3ede9a5e9e0ac369e909aec260ab319e86a77f6bcc5dcc606cf58e8b8dcc78af",
          "sha1": "2219919a66254fdc31b4413f15eb7faaab788ac0",
          "md5": "53f9fccf32e6cd2f17df65c8344f9e22"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:environment": "production",
        "environment": "production",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-tv-sdk-0.1.1.aar",
          "url": "android-tv-sdk-0.1.1.aar",
          "size": 58722,
          "sha512": "dd743d28cd1db5b988bcce13f4f8f1771d20971429425753a630f9d9fcf4fe17131bbf87f88271f5f6e61194067a650759a4dce8ee6236e1ca57a27efa5e2561",
          "sha256": "3ede9a5e9e0ac369e909aec260ab319e86a77f6bcc5dcc606cf58e8b8dcc78af",
          "sha1": "2219919a66254fdc31b4413f15eb7faaab788ac0",
          "md5": "53f9fccf32e6cd2f17df65c8344f9e22"
        }
      ]
    },
    {
      "name": "productionReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:environment": "production",
        "environment": "production",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-tv-sdk-0.1.1-sources.jar",
          "url": "android-tv-sdk-0.1.1-sources.jar",
          "size": 28473,
          "sha512": "270b24263bce1d544552de3bf219f00f94feaafd6942893b4131f8cd5df955c58efc59144823637e278261af2668a15ee3a76dda4c72a4a6bfac685c0cbb2a1d",
          "sha256": "bf6584c86e4b6b8385048809de5096ff560eecb75c4e81169575861244660c6e",
          "sha1": "bb26bbf2384810811faaa41718e7f96e0e6344a6",
          "md5": "89d3ae069f1f744b8c0352a4127c1d64"
        }
      ]
    }
  ]
}
